[package]
name = "memory_sqlite_rs"
version = "0.1.0"
authors = ["graves"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.25.3"
